### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JonathanGrossmanITC** [alex-lehan-bloom/Micro-Blog-In-React#1]
Hi Alex,

Nice work. Here is some feedback:

1. You should use self-closing tags when the innterHTML is empty. For instance, <PreviousTweets tweets={previousTweets} /> instead of <PreviousTweets tweets={previousTweets}></PreviousTweets>.

2. It looks like you're displaying spinners, alerts, and toggling buttons from enabled to disabled. Great job. Please make sure to consistently do that throughout your project, where applicable. Also, whenever you have an input, you should validate it. For instance, make sure the user can't submit an empty tweet or username, or can't submit a username of all spaces, or whatever the case may be. 

3. I like that you're becoming more familiar with the styling libraries/frameworks like bootstrap. I noticed that your CSS files are rather bare. At some point, you may want to practice your CSS more, in which case I recommend you write more of your own CSS.

4. Similarly, for react, you use  components for buttons, alerts, and spinners from third-party library. While that is an important tool to have, you should also consider practicing writing your own button, alert, and spinner components.

Great work!

**Comment by alex-lehan-bloom** [comment]
Great comments Jon! The changes have been implemented in commit:

3c8cce275a611d84703f32e95d15f6e599035eb0
